import BrandsBlock from '@/Components/Blocks/BrandsBlock';
import ServicesBlock from '@/Components/Blocks/ServicesBlock';
import TextWithImageBlock from '@/Components/Blocks/TextWithImageBlock';
import VideoHero from '@/Components/Hero/VideoHero';

const METADATA = {
  Url: 'https://pac-electrical.co.uk/ev',
  // SEO UPGRADE: Targeting the high-value "Installer" keyword + Location
  SiteName: 'EV Charger Installers Derby & Derbyshire | Power & Control',
  Description:
    'OZEV approved EV charger installers for homes and businesses across the East Midlands. Expert installation of Tesla, Zappi, Ohme, and more. Get your free quote today.',
};

export const metadata = {
  title: METADATA.SiteName,
  applicationName: METADATA.SiteName,
  description: METADATA.Description,
  referrer: 'origin-when-cross-origin',
  url: METADATA.Url,
  openGraph: {
    title: METADATA.SiteName,
    description: METADATA.Description,
    url: METADATA.Url,
    images: [
      {
        url: `${METADATA.Url}/images/sustain1.webp`, // Must be an absolute URL
        width: 800,
        height: 600,
      },
    ],
    locale: 'en_GB',
    type: 'website',
  },
};

export default function EVPage() {
  // SEO UPGRADE: EV Specific Service Schema for Google Knowledge Graph
  const evHubSchema = {
    '@context': 'https://schema.org/',
    '@type': 'Service',
    serviceType: 'EV Charging Point Installation',
    description:
      'Professional OZEV-approved installers for domestic and commercial EV charging stations in Derbyshire and the East Midlands.',
    provider: {
      '@type': 'Electrician',
      name: 'Power & Control Ltd',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Derby',
        addressRegion: 'Derbyshire',
      },
    },
    areaServed: [
      { '@type': 'State', name: 'Derbyshire' },
      { '@type': 'State', name: 'Nottinghamshire' },
      { '@type': 'State', name: 'Leicestershire' },
      { '@type': 'Region', name: 'East Midlands' },
    ],
  };

  return (
    <div>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(evHubSchema) }}
      />

      <VideoHero margin height="70vh">
        {/* SEO UPGRADE: Direct Keyword Targeting for Regional Search */}
        <h1>EV Charger Installation Derbyshire</h1>
        <h3>Power your next adventure with smart charging</h3>
      </VideoHero>

      <div style={{ marginTop: '100px' }} />

      <TextWithImageBlock
        image="/images/ev/ev.webp"
        title="OZEV Approved EV Charging Experts"
        text={[
          'With the rapid increase in electric vehicles across the UK, more homeowners and businesses are looking to install reliable domestic or commercial EV chargers. At Power & Control, we specialise in OZEV-approved installations that make transitioning to electric transport effortless.',
          'Based in Derby, our NICEIC-approved engineers provide a full turnkey service across the East Midlands. We install a wide range of smart chargers, ensuring your system is optimised for speed, safety, and integration with renewable energy sources like solar PV.',
        ]}
      />

      <div style={{ marginTop: '100px' }} />

      <ServicesBlock
        title="Your EV Charge Point Options"
        services={[
          {
            title: 'Easee',
            link: '/ev',
            description:
              'The Easee charger is reliable and durable for both domestic and commercial EV charging.',
            charger: 'easee.webp',
          },
          {
            title: 'Zappi',
            link: '/ev',
            charger: 'zappi.webp',
            description:
              'The zappi is a British-made smart EV charger, able to operate on electricity generated by your solar panels as well as the National Grid.',
          },
          {
            title: 'Tesla',
            link: '/ev',
            charger: 'tesla.webp',
            description:
              'Official Tesla Wall Connector installations for seamless home charging for all Tesla models.',
          },
          {
            title: 'Hypervolt',
            link: '/ev',
            charger: 'hypervolt.webp',
            description:
              'Hypervolt chargers use your Wi-Fi or Ethernet network to offer a seamless, app-connected charging experience.',
          },
          {
            title: 'Ohme',
            link: '/ev',
            charger: 'ohme.webp',
            description:
              'Take control of your energy costs with Ohme smart chargers, designed to integrate with off-peak time-of-use tariffs.',
          },
          {
            title: 'Rolec QUBEV',
            link: '/ev',
            charger: 'rolec.webp',
            description:
              'The QUBEV is an affordable and compact entry-level charging solution, perfect for straightforward home installations.',
          },
          {
            title: 'Andersen',
            link: '/ev',
            charger: 'andersen.webp',
            description:
              'Andersen chargers are premium, intelligent charge points dedicated to high-end aesthetics and superior build quality.',
          },
          {
            title: 'Project EV',
            link: '/ev',
            charger: 'project-ev.webp',
            description:
              'Project EV provides versatile chargers for both domestic and commercial environments, with outputs ranging from 7.3kW AC to 300kW DC.',
          },
          {
            title: 'EO Mini Pro 2',
            link: '/ev',
            charger: 'eo-mini-pro-2.webp',
            description:
              'The EO Mini Pro 2 is one of the world’s smallest smart chargers, perfect for drivers who value a discreet, compact installation.',
          },
          {
            title: 'Sync EV',
            link: '/ev',
            charger: 'sync-ev.webp',
            description:
              'Sync EV provides discreet, weatherproof chargers that offer smart app control for both the home and the workplace.',
          },
        ]}
      />

      <BrandsBlock
        title="Charging Sectors"
        brands={[
          {
            link: '/ev/domestic',
            heroImage: '/images/ev/domev.webp',
            alt: 'Domestic EV Charge Point Installation',
            name: 'Domestic',
          },
          {
            link: '/ev/commercial',
            heroImage: '/images/ev/comev.webp',
            alt: 'Commercial EV Fleet Charging Solutions',
            name: 'Commercial',
          },
        ]}
      />

      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://www.phoenix-fc.co.uk/finance_landing?b=C8B8CE9EE290400B&t=2A9C018824984F2CB1EEFAFA"
        style={{ fontSize: '18px' }}
      >
        <img
          src="/images/finance-banners/ev_banner.png"
          alt="We offer finance options for EV charger installations."
          style={{ width: '100%', marginTop: '10px', maxWidth: '1200px' }}
        />
      </a>
    </div>
  );
}
