import BrandsBlock from '@/Components/Blocks/BrandsBlock';
import ServicesBlock from '@/Components/Blocks/ServicesBlock';
import TextWithImageBlock from '@/Components/Blocks/TextWithImageBlock';
import VideoHero from '@/Components/Hero/VideoHero';

const METADATA = {
  Url: 'https://pac-electrical.co.uk/ev',
  SiteName: 'EV Charge Points - Power & Control',
  Description:
    'Trusted electrical and renewable energy contractors, Power & Control, serving the Midlands and beyond. Specialising in solar, EV charging, and commercial electrical.',
};
export const metadata = {
  title: METADATA.SiteName,
  applicationName: METADATA.SiteName,
  description: METADATA.Description,
  referrer: 'origin-when-cross-origin',
  url: METADATA.Url,
  openGraph: {
    title: METADATA.SiteName,
    description: METADATA.Description,
    url: METADATA.Url,
    images: [
      {
        url: `${METADATA.Url}/images/sustain1.webp`, // Must be an absolute URL
        width: 800,
        height: 600,
      },
    ],
    locale: 'en_GB',
    type: 'website',
  },
};
export default function EVPage() {
  return (
    <div>
      <VideoHero margin height="70vh">
        <h1>EV Charging</h1>
        <h3>Power your next adventure</h3>
      </VideoHero>
      <div style={{ marginTop: '100px' }} />
      <TextWithImageBlock
        image="/images/ev/ev.webp"
        title="EV Charging Experts"
        text={[
          'With the increase in electric vehicles, many people are looking to install domestic or commercial EV chargers to their properties. All electric vehicles require an EV charger to charge their battery. Installing a charger at your home or workplace will mean owning an electric vehicle is effortless.',
          'At Power and Control, we specialise in domestic and commercial EV charger installations. We install a wide range of chargers.',
        ]}
      />
      <div style={{ marginTop: '100px' }} />
      <ServicesBlock
        title="Your EV Charge Point Options"
        services={[
          {
            title: 'Easee',
            link: '/ev',
            description:
              'The Easee charger is reliable and durable for both domestic and commercial EV charging.',
            charger: 'easee.webp',
          },
          {
            title: 'Zappi',
            link: '/ev',
            charger: 'zappi.webp',
            description:
              'The zappi charger is a smart EV charger, able to operate on electricity generated by solar, as well as from the National Grid.',
          },
          {
            title: 'Tesla',
            link: '/ev',
            charger: 'tesla.webp',
            description: '',
          },
          {
            title: 'Hypervolt',
            link: '/ev',
            charger: 'hypervolt.webp',
            description:
              'Hypervolt chargers use your wi-fi or ethernet network to offer a seamless connected experience at no extra cost.',
          },
          {
            title: 'Ohme',
            link: '/ev',
            charger: 'ohme.webp',
            description:
              'Use Ohme chargers to take control of your home EV charging system.',
          },
          {
            title: 'Rolec QUBEV',
            link: '/ev',
            charger: 'rolec.webp',
            description: '',
          },
          {
            title: 'Andersen',
            link: '/ev',
            charger: 'andersen.webp',
            description:
              'Andersen chargers are intelligent charge points, dedicated to designing and making EV chargers that look good and work great.',
          },
          {
            title: 'Project EV',
            link: '/ev',
            charger: 'project-ev.webp',
            description:
              'Project EV chargers are great for both domestic and commercial environments, with ranges from 7.3kw AC to 300kw DC.',
          },
          {
            title: 'EO Mini Pro 2',
            link: '/ev',
            charger: 'eo-mini-pro-2.webp',
            description:
              'The EO Mini Pro 2 is the world’s smallest smart charger, perfect for the everyday electric vehicle driver.',
          },
          {
            title: 'Sync EV',
            link: '/ev',
            charger: 'sync-ev.webp',
            description:
              'Sync EV chargers provide discreet, compact, weatherproof chargers for both the home and the workplace.',
          },
        ]}
      />
      <BrandsBlock
        title="Sectors"
        brands={[
          {
            link: '/ev/domestic',
            heroImage: '/images/ev/domev.webp',
            alt: 'Domestic EV Charge Points from Power & Control',
            name: 'Domestic',
          },
          {
            link: '/ev/commercial',
            heroImage: '/images/ev/comev.webp',
            alt: 'Comercial EV Charge Points from Power & Control',
            name: 'Commercial',
          },
        ]}
      />
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://www.phoenix-fc.co.uk/finance_landing?b=C8B8CE9EE290400B&t=2A9C018824984F2CB1EEFAFA"
        style={{ fontSize: '18px' }}
      >
        <img
          src="/images/finance-banners/ev_banner.png"
          alt="We offer finance."
          style={{ width: '100%', marginTop: '10px', maxWidth: '1200px' }}
        />
      </a>
    </div>
  );
}
