import VideoHero from '@/Components/Hero/VideoHero';

export default function BlockManager({ blocks }) {
  if (!blocks || blocks.length === 0) {
    return null;
  }

  return (
    <div>
      {blocks.map((block) => {
        // This '_key' is automatically generated by Sanity for every item in an array
        const key = block._key;

        // "heroBlock" matches the 'name' we defined in your page.ts schema
        switch (block._type) {
          case 'heroBlock':
            return (
              <VideoHero
                key={key}
                title={block.title}
                subtitle={block.subtitle}
                videoUrl={block.video?.asset?._ref} // We need to fix the URL fetch here
              />
            );

          // Case: 'textWithImage': return <TextWithImage ... />

          default:
            return <div key={key}>Block type "{block._type}" not found</div>;
        }
      })}
    </div>
  );
}
